### ISSUE TITLE
PoCo Protocol 

### ISSUE THREAD

**Issue by lodygens** [iExecBlockchainComputing/iexec-doc#11]
Globally, please correct english ("amongs" and other "enshure" or "dealid", "betwenn"  etc.)

1) Objectives
- Result certification : the term "result certification" may be ambiguous : the PoCo does not certify the retulst itself, but the fact that a certain amount of workers gave the same result.
By the way the chapter "Replication & Trust" starts with "likelihood of a result to be valid" which is more exact.
- Secure Payment: the protocol ensures all payments occur, not only the worker

2) Overview
- actors should be first introduced to ease understanding the document and the nominal workflow (what is the clerk and escrow and how they work)
- determinism must be introduced  since it is the base of the PoCo
- "are requires" => "are required"
- nobody knows what is "V3-alpha" ...
- "The consensus timer starts when the deal is signed". When is it signed? I found no clue on the nominal workflow (I guess it is the matchOrder() call...)
- "Given a dealid and.." : given what?
- "The scheduler designates workers that an participate to this task" : what ?
- "This is necessary to achieve consensus on non deterministic applications" : determinism must be introduced before this sentence 

It may be interesting to draw the consensus time line showing contribution and reveal periods.

3) Parameters
Parameters of the PoCo must be set when, how and where?
- WORKERPOOL_STAKE_RATIO and workerStakeRatioPolicy are the same? Is it only a typo error in the text? Or are they two different things?

**Comment by ericr6** [comment]
done
