### ISSUE TITLE
PoCo Brokering

### ISSUE THREAD

**Issue by lodygens** [iExecBlockchainComputing/iexec-doc#14]
1) It would be nice to introduce in one sentence the brokering as found in the medium post for example : "The ‘brokering’ aspect of the iExec solution addresses a simple issue: to provide a mechanism for different actors to reach an agreement"

2) The notion of "ask" and "bid" must be introduced before this chapter (or as introduction to this chapter)

3) Ah! The clerk is finaly defined here, a little bit late :p

4) We may introduce another tag example (GPU ? )

5) "There are 4 types of orders corresponding to the 4 actors": unfortunately actors have not been introduced :(

**Comment by ericr6** [comment]
fixed in the last important  update
