### ISSUE TITLE
Computing resource pricing

### ISSUE THREAD

**Issue by lodygens** [iExecBlockchainComputing/iexec-doc#30]
Ca c'est juste carrément faux, si je ne m'abuse: 
This materializes in your machine executing computational tasks in exchange for a price freely determined by you.

Ce n'est pas le worker qui fixe le prix, c'est le scheduler

**Comment by lodygens** [comment]
D'ailleurs le paragraphe suivant le dit bien: c'est le pool manager qui définit les prix
"Worker pools are made up of multiple individual machines. They are led by a Pool manager, a lead entity that organizes the workload and signals how many tasks it is able to process and at which price"

**Comment by ericr6** [comment]
done
