### ISSUE TITLE
Wallet

### ISSUE THREAD

**Issue by lodygens** [iExecBlockchainComputing/iexec-doc#47]
je pense qu'on devrait ajouter un paragraphe sur l'exportation du wallet metamask et l'importation dans le worker

**Comment by lodygens** [comment]
d'autre part les useful links : il faut ecrire en tres tres gros que les faucets ne sont utilisables que sur les reseaux de test uniquement afin que personne ne pense qu'on donne des brouzoufs.
j'ai bien vu que le texte contient "test" mais j'aurai mis ça plus en valeur; par ex une phrase avant les 2 bullets pour insister bien lourdement

**Comment by lodygens** [comment]
je viens d'importer avec succes mon wallet metamask dans la VM
1) j'ai exporte la cle privee de metamask de mon PC
2) j'ai du installer iexec SDK dans la VM
3) j'ai fait iexec wallet import ma_cle_privee_de_metamask

**Comment by ericr6** [comment]
implemented
